name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: macos-26
    
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          install: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6
      - name: Build
        run: ./gradlew macosUniversalBinary

      - name: Upload Binaries
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          # TODO will need to work out how to sign these
          name: MacOs Universal Binary
          path: 'build/bin/macos-universal/brew-update-all-the-things'
